<?xml version='1.1' encoding='UTF-8'?>
<Tag plugin="workflow-support@838.va_3a_087b_4055b">
  <node class="cps.n.StepEndNode" plugin="workflow-cps@2801.vf82a_b_b_e3e8a_5">
    <parentIds>
      <string>20</string>
    </parentIds>
    <id>21</id>
    <startId>7</startId>
  </node>
  <actions>
    <wf.a.TimingAction plugin="workflow-api@1200.v8005c684b_a_c6">
      <startTime>1676960282095</startTime>
    </wf.a.TimingAction>
    <wf.a.ErrorAction plugin="workflow-api@1200.v8005c684b_a_c6">
      <error class="hudson.AbortException">
        <detailMessage>script returned exit code 2</detailMessage>
        <stackTrace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.handleExit(DurableTaskStep.java:664)</trace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.check(DurableTaskStep.java:610)</trace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.run(DurableTaskStep.java:554)</trace>
          <trace>java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)</trace>
          <trace>java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)</trace>
          <trace>java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)</trace>
          <trace>java.base/java.lang.Thread.run(Thread.java:829)</trace>
        </stackTrace>
        <suppressedExceptions class="empty-list"/>
      </error>
    </wf.a.ErrorAction>
  </actions>
</Tag>